#!/bin/bash
#
# picnic - deploy git without sudo/root
#

INSTALL_DIR=${INSTALL_DIR:-"$HOME/picnic-tools"}
WORK_SPACE=${WORK_SPACE:-"/tmp/picnic"}
LOGFILE="$WORK_SPACE/install.log"

function warn {
  # color:yellow
  echo -e "\033[33mWarning\033[m" "$*"
}

function error {
  # color:red
  echo -e "\033[31mError\033[m" "$*"
}

function success {
  # color:green
  echo -e "\033[32mSuccess\033[m" "$*"
}

function show_result {
  case "$1" in
  0 )
    success "installed $2 to $INSTALL_DIR"
    ;;
  * )
    error "failed install $2 ith $1, see $LOGFILE to more info"
    ;;
  esac
}

function check_os {
  case ${OSTYPE} in
  linux* )
    success "The system is $OSTYPE, ready to deploy"
    ;;
  * )
    error "$OSTYPE is NOT supported, exitting"
    exit 1
    ;;
  esac
}

function check_available {
  which "$1" &>/dev/null
  return $?
}

package_zlib="http://zlib.net/zlib-1.2.8.tar.gz"
package_git="https://www.kernel.org/pub/software/scm/git/git-2.8.1.tar.gz"
package_expat="https://launchpad.net/ubuntu/+archive/primary/+files/expat_2.1.0.orig.tar.gz"
package_openssl="https://www.openssl.org/source/openssl-1.0.2g.tar.gz"
package_curl="http://www.execve.net/curl/curl-7.48.0.tar.gz"

function package_download {
  cd "$WORK_SPACE"
  # ordered by file size
  download "$package_curl" &
  download "$package_git" &
  download "$package_openssl" &
  download "$package_zlib" &
  download "$package_expat" &
  wait
}

function download {
  wget "$1" &>/dev/null &&
  success "download source file: $(basename -- $1)"
}

function install_zlib {
  local result=1
  local tar_package="$(basename $package_zlib)"
  local package="${tar_package%.tar.gz}"
  cd "$WORK_SPACE"
  echo "installing zlib..."
  {
    echo "=========INSTALLING ZLIB=========" &&
    tar zxf "$tar_package" &&
    cd "$package" &&
    ./configure --prefix="$INSTALL_DIR" &&
    make &&
    make install
    result=$?
  } > "$WORK_SPACE/tmp.$$" 2>&1
  cat "$WORK_SPACE/tmp.$$" >> "$LOGFILE"
  show_result "$result" "zlib"
}

function install_git {
  local result=1
  local tar_package="$(basename $package_git)"
  local package="${tar_package%.tar.gz}"
  cd "$WORK_SPACE"
  echo "installing git..."
  {
    echo "=========INSTALLING GIT=========" &&
    tar zxf "$tar_package" &&
    cd "$package" &&
    ./configure --prefix="$INSTALL_DIR" --with-expat="$INSTALL_DIR" --with-curl="$INSTALL_DIR" &&
    make CURLDIR="$INSTALL_DIR" &&
    make install
    result=$?
  } > "$WORK_SPACE/tmp.$$" 2>&1
  cat "$WORK_SPACE/tmp.$$" >> "$LOGFILE"
  show_result "$result" "git"
}

function install_curl {
  local result=1
  local tar_package="$(basename $package_curl)"
  local package="${tar_package%.tar.gz}"
  cd "$WORK_SPACE"
  echo "installing curl..."
  {
    echo "=========INSTALLING CURL=========" &&
    tar zxf "$tar_package" &&
    cd "$package" &&
    ./configure --with-ssl="$INSTALL_DIR" --prefix="$INSTALL_DIR" &&
    make &&
    make install
    result=$?
  } > "$WORK_SPACE/tmp.$$" 2>&1
  cat "$WORK_SPACE/tmp.$$" >> "$LOGFILE"
  show_result "$result" "curl"
}

function install_openssl {
  local result=1
  local tar_package="$(basename $package_openssl)"
  local package="${tar_package%.tar.gz}"
  cd "$WORK_SPACE"
  echo "installing openssl..."
  {
    echo "=========INSTALLING SSL=========" &&
    tar zxf "$tar_package" &&
    cd "$package" &&
    ./config --prefix="$INSTALL_DIR" shared zlib-dynamic &&
    make &&
    make install
    result=$?
  } > "$WORK_SPACE/tmp.$$" 2>&1
  cat "$WORK_SPACE/tmp.$$" >> "$LOGFILE"
  show_result "$result" "openssl"
}

function install_expat {
  local result=1
  local tar_package="$(basename $package_expat)"
  local package="${tar_package%.tar.gz}"
  cd "$WORK_SPACE"
  echo "installing expat..."
  {
    echo "=========INSTALLING EXPAT=========" &&
    tar zxf "$tar_package" &&
    cd "$package" &&
    ./configure --prefix="$INSTALL_DIR" --disable-static &&
    make &&
    make install
    result=$?
  } > "$WORK_SPACE/tmp.$$" 2>&1
  cat "$WORK_SPACE/tmp.$$" >> "$LOGFILE"
  show_result "$result" "expat"
}

# SUBCOMMANDS

# download source file only
function picnic-getpack {
  check_os
  mkdir -p "$WORK_SPACE"
  package_download
  success "source file downloaded."
}

# download and install packages
#
# dependencies tree
#
#   git
#   ├── curl
#   │   └── openssl
#   │       └── zlib
#   └── expat
#
function picnic-unpack {
  check_os
  mkdir -p "$INSTALL_DIR"
  mkdir -p "$WORK_SPACE"
  package_download
  export CPPFLAGS="-I$INSTALL_DIR/include" LDFLAGS="-L$INSTALL_DIR/lib" LD_LIBRARY_PATH="$INSTALL_DIR/lib"
  echo "picnic unpack $(date)" > "$LOGFILE"
  install_zlib
  install_openssl
  install_curl
  install_expat
  install_git
  # echo "PATH=$PATH:$INSTALL_DIR/bin" >> "$HOME/.$(basename $SHELL)rc"
}

# reinstall packages
function picnic-reunpack {
  picnic-remove
  picnic-unpack
}

# remove packages
function picnic-remove {
  if [ -d "$INSTALL_DIR" ]; then
    rm -rf "$INSTALL_DIR"
  fi
}

function picnic-help {
  echo "picnic-1.1.0"
  echo "  unpack: install from source"
  echo "  remove: remove files"
}

# MAIN

SUBCOMMAND=""
ARGS=()
while [ $# -gt 0 ]
do
  case "$1" in
  --help | --version | -V )
    picnic-help
    exit 0
    ;;
  * )
    if [ -z "$SUBCOMMAND" ]; then
      SUBCOMMAND="$1"
    else
      ARGS+=( "$1" )
    fi
    shift
    ;;
  esac
done

function invoke_subcommand {
  local SUBCOMMAND="${@:1:1}"
  local ARGS=( "${@:2}" )
  local ACTION="picnic-${SUBCOMMAND:-help}"
  if type "$ACTION" &>/dev/null; then
    "$ACTION" "${ARGS[@]}"
  else
    error "unknown command: $SUBCOMMAND"
  fi
}

invoke_subcommand "$SUBCOMMAND" "${ARGS[@]}"
