#!/bin/bash

function warn {
  # color:yellow
  echo -e "\033[33mWarning\033[m" "$*"
}

function error {
  # color:red
  echo -e "\033[31mError\033[m" "$*"
}

function success {
  # color:green
  echo -e "\033[32mSuccess\033[m" "$*"
}

function show_result {
  case "$1" in
    0)
      success "installed $2 to $HOME/picnic-tools"
      ;;
    *)
      error "failed install $2 ith $1, see ~/picnic-tmp/install.log to more info"
      ;;
  esac
}

function check_os {
  case ${OSTYPE} in
    linux*)
      success "The system is $(OSTYPE), ready to deploy"
      ;;
    *)
      error "$OSTYPE is NOT supported, exitting"
      exit 1
      ;;
  esac
}

function check_available {
  which "$1" &>/dev/null
  return $?
}

function package_download {
  cd ~/picnic-tmp
  wget "http://zlib.net/zlib-1.2.8.tar.gz"
  wget "https://www.kernel.org/pub/software/scm/git/git-2.8.1.tar.gz"
  wget -O expat-2.1.0.tar.gz "http://osdn.jp/frs/g_redir.php?m=kent&f=%2Fexpat%2Fexpat%2F2.1.0%2Fexpat-2.1.0.tar.gz"
  wget "https://www.openssl.org/source/openssl-1.0.2g.tar.gz"
  wget "http://www.execve.net/curl/curl-7.48.0.tar.gz"
}

function install_zlib {
  cd ~/picnic-tmp
  echo "=========INSTALLING ZLIB=========" >> ~/picnic-tmp/install.log 
  tar zxf zlib-1.2.8.tar.gz >> ~/picnic-tmp/install.log &&
  cd zlib-1.2.8 &&
  ./configure --prefix=$HOME/picnic-tools >> ~/picnic-tmp/install.log &&
  make >> ~/picnic-tmp/install.log &&
  make install >> ~/picnic-tmp/install.log
  show_result $? "zlib"
}


function install_git {
  cd ~/picnic-tmp
  echo "=========INSTALLING GIT=========" >> ~/picnic-tmp/install.log 
  tar zxf git-2.8.1.tar.gz >> ~/picnic-tmp/install.log &&
  cd git-2.8.1 &&
  ./configure --prefix=$HOME/picnic-tools --with-curl=$HOME/picnic-tools/ --with-expat=$HOME/picnic-tools  >> ~/picnic-tmp/install.log &&
  make CURLDIR=$HOME/picnic-tools >> ~/picnic-tmp/install.log &&
  make install  >> ~/picnic-tmp/install.log
  show_result $? "git"
}

function install_curl {
  cd ~/picnic-tmp
  echo "=========INSTALLING CURL=========" >> ~/picnic-tmp/install.log 
  tar zxf curl-7.48.0.tar.gz >> ~/picnic-tmp/install.log &&
  cd curl-7.48.0 &&
  ./configure --with-ssl=$HOME/picnic-tools --prefix=$HOME/picnic-tools >> ~/picnic-tmp/install.log &&
  make >> ~/picnic-tmp/install.log &&
  make install >> ~/picnic-tmp/install.log
  show_result $? "curl"
}

function install_ssl {
  cd ~/picnic-tmp
  echo "=========INSTALLING SSL=========" >> ~/picnic-tmp/install.log 
  tar zxf openssl-1.0.2g.tar.gz >> ~/picnic-tmp/install.log &&
  cd openssl-1.0.2g &&
  ./config --prefix=$HOME/picnic-tools shared zlib-dynamic >> ~/picnic-tmp/install.log &&
  make >> ~/picnic-tmp/install.log &&
  make install >> ~/picnic-tmp/install.log
  show_result $? "ssl"
}

function install_expat {
  cd ~/picnic-tmp
  echo "=========INSTALLING EXPAT=========" >> ~/picnic-tmp/install.log 
  tar zxf expat-2.1.0.tar.gz >> ~/picnic-tmp/install.log &&
  cd expat-2.1.0 &&
  ./configure --prefix=$HOME/picnic-tools --disable-static >> ~/picnic-tmp/install.log &&
  make >> ~/picnic-tmp/install.log &&
  make install >> ~/picnic-tmp/install.log
  show_result $? "expat"
}

# SUBCOMMANDS

function picnic-getpack {
  check_os
  mkdir ~/picnic-tmp
  package_download
  success "source file downloaded."
}

function picnic-unpack {
  check_os
  mkdir ~/picnic-tmp
  mkdir ~/picnic-tools
  package_download
  export CPPFLAGS="-I$HOME/picnic-tools/include" LDFLAGS="-L$HOME/picnic-tools/lib -lcurl -lidn -lssl -lcrypto -lz"
  echo "picnic unpack $(date)" > ~/picnic-tmp/install.log
  install_zlib
  install_ssl
  install_curl
  install_expat
  install_git
  # echo "PATH=$PATH:~/picnic/bin" >> "~/.$(basename $SHELL)rc"
}

function picnic-reunpack {
  check_os
  if [ ! -e picnic-tmp/ ]; then
    echo "packages not found in local, try 'picnic unpack'"
    exit 1
  fi
  if [ -e picnic-tools ];then
    rm -rf picnic-tools/
  fi
  mkdir ~/picnic-tools
  export CPPFLAGS="-I$HOME/picnic-tools/include" LDFLAGS="-L$HOME/picnic-tools/lib"
  echo "picnic reunpack $(date)" > ~/picnic-tmp/install.log
  install_zlib
  install_ssl
  install_curl
  install_expat
  install_git
}

function picnic-test {
  cd ~/picnic-tools/bin
  ./git clone https://github.com/nobuyo/picnic.git || exit 1
  success "Git installed successfully"
  exit 0
}

function picnic-remove {
  if [ -e ~/picnic-tools ]; then
    rm -rf ~/picnic-*
  fi
}

# for dev
function picnic-update {
  dir="$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)"
  me=$dir/"$(basename $0)"
  mv $me $dir/picnic-old
  wget -O $me "https://raw.githubusercontent.com/nobuyo/picnic/master/picnic"
  if [ $? -ne 0 ]; then
    error "pinic Could not found, reverting"
    mv $dir/pinic-old $me
    exit 1
  fi
  chmod +x $me
  success "Updated picnic"
}

function picnic-help {
  echo "picnic-0.1.0"
  echo "  unpack: install from source"
  echo "  remove: remove files"
}

# MAIN

SUBCOMMAND=""
ARGS=()
while [ $# -gt 0 ]
do
  case "$1" in

    --help|--version|-V)
      picnic-help
      exit 0
    ;;

    *)
      if [ -z "$SUBCOMMAND" ]; then
        SUBCOMMAND="$1"
      else
        ARGS+=( "$1" )
      fi
      shift
    ;;
  esac
done

function invoke_subcommand {
  local SUBCOMMAND="${@:1:1}"
  local ARGS=( "${@:2}" )
  local ACTION="picnic-${SUBCOMMAND:-help}"
  if type "$ACTION" &>/dev/null; then
    "$ACTION" "${ARGS[@]}"
  else
    error "unknown command: $SUBCOMMAND"
  fi
}

invoke_subcommand "$SUBCOMMAND" "${ARGS[@]}"
