#!/bin/bash
#
# picnic - deploy git without sudo/root
#

INSTALL_DIR=${INSTALL_DIR:-"$HOME/git-tools"}
WORK_SPACE=${WORK_SPACE:-"/tmp/picnic"}
LOGFILE="$WORK_SPACE/install.log"

function warn {
  # color:yellow
  echo -e "\033[33mWarning\033[m" "$*"
}

function error {
  # color:red
  echo -e "\033[31mError\033[m" "$*"
}

function success {
  # color:green
  echo -e "\033[32mSuccess\033[m" "$*"
}

# show_result <status> <package>
function show_result {
  case "$1" in
  0 ) success "installed $2 to $INSTALL_DIR" ;;
  * ) error   "failed install $2, see $LOGFILE to more info" ;;
  esac
}

function check_os {
  case "$OSTYPE" in
  linux* )
    success "The system is $OSTYPE, ready to deploy"
    ;;
  * )
    error "$OSTYPE is NOT supported, exitting"
    exit 1
    ;;
  esac
}

# <package> := curl | expat | git | openssl | zlib
package_curl="http://www.execve.net/curl/curl-7.48.0.tar.gz" # 404
package_expat="http://osdn.jp/frs/g_redir.php?m=kent&f=%2Fexpat%2Fexpat%2F2.1.0%2Fexpat-2.1.0.tar.gz"
package_git="https://www.kernel.org/pub/software/scm/git/git-2.12.2.tar.gz"
package_openssl="https://www.openssl.org/source/openssl-1.1.0e.tar.gz"
package_zlib="http://zlib.net/zlib-1.2.11.tar.gz"

# download <package>
function download {
  local package=$1
  local package_url=$(eval echo '$package_'$1)
  wget -O "$package.tar.gz" "$package_url" &>/dev/null &&
  success "download source file: $package.tar.gz"
}

function download_package {
  cd "$WORK_SPACE"
  # ordered by file size
  download "curl" &
  download "git" &
  download "openssl" &
  download "zlib" &
  download "expat" &
  wait
}

# install <package>
function install {
  local result=1
  local package="$1"
  local tar_package="$package.tar.gz"
  cd "$WORK_SPACE"
  echo "installing $package..."
  {
    echo "=========INSTALLING $package=========" &&
    mkdir -p "$package" &&
    tar zxf "$tar_package" -C "$package" --strip-components 1 &&
    cd "$package" &&
    ${CONFIGURE:-./configure} &&
    ${MAKE:-make} &&
    make install
    result=$?
  } > "$WORK_SPACE/tmp.$$" 2>&1
  cat "$WORK_SPACE/tmp.$$" >> "$LOGFILE"
  show_result "$result" "$package"
}

# dependencies tree
#
#   git
#   ├── curl
#   │   └── openssl
#   │       └── zlib
#   └── expat
#
function install_package {
  export CPPFLAGS="-I$INSTALL_DIR/include" LDFLAGS="-L$INSTALL_DIR/lib" LD_LIBRARY_PATH="$INSTALL_DIR/lib"
  echo "picnic unpack $(date)" > "$LOGFILE"

  CONFIGURE="./configure --prefix="$INSTALL_DIR"" \
    install "zlib"
  CONFIGURE="./config --prefix="$INSTALL_DIR" shared zlib-dynamic" \
    install "openssl"
  CONFIGURE="./configure --with-ssl="$INSTALL_DIR" --prefix="$INSTALL_DIR"" \
    install "curl"
  CONFIGURE="./configure --prefix="$INSTALL_DIR" --disable-static" \
    install "expat"
  CONFIGURE="./configure --prefix="$INSTALL_DIR" --with-expat="$INSTALL_DIR" --with-curl="$INSTALL_DIR"" \
  MAKE="make CURLDIR="$INSTALL_DIR"" \
    install "git"

  echo "You will need to manually adapt your shell's environment"
  echo "to work with picnic-tools."
  echo "Add $INSTALL_DIR/bin to your PATH."
  echo ""
  echo "    export PATH=\"\$PATH:$INSTALL_DIR/bin\""
  echo ""
}

# SUBCOMMANDS

# download source file only
function picnic-getpack {
  check_os
  mkdir -p "$WORK_SPACE"
  download_package
  success "source file downloaded."
}

# download and install packages
function picnic-unpack {
  check_os
  mkdir -p "$INSTALL_DIR"
  mkdir -p "$WORK_SPACE"
  download_package
  install_package
}

# reinstall packages
function picnic-reunpack {
  picnic-remove
  picnic-unpack
}

# remove packages
function picnic-remove {
  test -d "$INSTALL_DIR" && rm -rf "$INSTALL_DIR"
  test -d "$WORK_SPACE"  && rm -rf "$WORK_SPACE"
}

# show version and help
function picnic-help {
  echo "picnic-1.1.0"
  echo "  unpack: install from source"
  echo "  remove: remove files"
}

# MAIN

SUBCOMMAND=""
ARGS=()
while [ $# -gt 0 ]
do
  case "$1" in
  --help | --version | -V )
    picnic-help
    exit 0
    ;;
  * )
    if [ -z "$SUBCOMMAND" ]; then
      SUBCOMMAND="$1"
    else
      ARGS+=( "$1" )
    fi
    shift
    ;;
  esac
done

function invoke_subcommand {
  local SUBCOMMAND="${@:1:1}"
  local ARGS=( "${@:2}" )
  local ACTION="picnic-${SUBCOMMAND:-help}"
  if type "$ACTION" &>/dev/null; then
    "$ACTION" "${ARGS[@]}"
  else
    error "unknown command: $SUBCOMMAND"
  fi
}

invoke_subcommand "$SUBCOMMAND" "${ARGS[@]}"
